In [1]:
from text2sql import hello
print(hello.message)

hello, world!


In [2]:
from dotenv import load_dotenv
load_dotenv("local.env")

True

In [3]:
import os
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

from text2sql.engine.embeddings import AzureEmbedder

In [4]:
api_key=os.environ.get("AZURE_OPENAI_API_KEY")
azure_endpoint=os.environ.get("AZURE_OPENAI_API_ENDPOINT")
api_version=os.environ.get("AZURE_OPENAI_API_VERSION")
model=os.environ.get("AZURE_OPENAI_MODEL")
print(f"api_key: {api_key[:5]}")
print(f"azure_endpoint: {azure_endpoint}")
print(f"api_version: {api_version}")
print(f"model: {model}")

api_key: 3dcb0
azure_endpoint: https://gena-gpt-2.openai.azure.com/
api_version: 2024-06-01
model: gena-text-embedding-3-small


In [5]:
embedder = AzureEmbedder(
    api_key=os.environ.get("AZURE_OPENAI_API_KEY"),
    azure_endpoint=os.environ.get("AZURE_OPENAI_API_ENDPOINT"),
    api_version=os.environ.get("AZURE_OPENAI_API_VERSION"),
    model=os.environ.get("AZURE_OPENAI_MODEL"),
    batch_size=1,
)

In [6]:
texts = [
    "The Trojans, after a seven years’ voyage, set sail for Italy, but are overtaken by a dreadful storm, which Aeolus raises at the request of Juno.",
    "트로이아군은 7년간의 항해 끝에 이탈리아로 항해를 떠났지만 주노의 요청으로 무서운 폭풍에 추월당합니다.",
    "enus complains to Jupiter of her son’s misfortunes. Jupiter comforts her, and sends Mercury to procure him a kind reception among the Carthaginians.",
    "에누스는 주피터에게 아들의 불행에 대해 불평합니다. 주피터는 그녀를 위로하고 머큐리를 보내 카르타고 인들 사이에서 아들을 친절하게 맞이합니다.",
]

In [7]:
embeddings = embedder.embed(texts, verbose=True)

100%|██████████| 4/4 [00:01<00:00,  2.51it/s]


In [8]:
print(cosine_similarity(embeddings, embeddings))

[[1.         0.31451158 0.46395302 0.07135151]
 [0.31451158 1.         0.1697474  0.22863711]
 [0.46395302 0.1697474  1.         0.31457679]
 [0.07135151 0.22863711 0.31457679 1.        ]]
